# Generated by Django 2.1.4 on 2024-05-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumCovers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcover',
            name='cover_url',
            field=models.CharField(max_length=1000),
        ),
    ]
