# Generated by Django 3.1.3 on 2024-05-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albumCovers', '0004_auto_20240507_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumcover',
            old_name='album_name',
            new_name='albumName',
        ),
    ]
