# Generated by Django 3.1.3 on 2024-05-16 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albumCovers', '0005_auto_20240516_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumcover',
            options={},
        ),
        migrations.RemoveField(
            model_name='albumcover',
            name='created_at',
        ),
        migrations.AddField(
            model_name='albumcover',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
